export const weatherData = [
    {
        cityName: "Colombo, LK",
        weatherDescription: "Cloudy",
        temp: 33.0,
        tempMax: 34.0,
        tempMin: 29.8,
        humidity: 82,
        pressure: 1012,
        visibility: 40,
        windSpeed: 6.5,
        windDegree: 215,
        sunrise: "06:03 AM",
        sunset: "06:45 PM"
    },
    {
        cityName: "Tokyo, JP",
        weatherDescription: "Clear",
        temp: 8.6,
        tempMax: 10.0,
        tempMin: 6.2,
        humidity: 60,
        pressure: 1018,
        visibility: 50,
        windSpeed: 3.0,
        windDegree: 120,
        sunrise: "05:30 AM",
        sunset: "06:30 PM"
    },
    {
        cityName: "Liverpool, GB",
        weatherDescription: "Rain",
        temp: 16.5,
        tempMax: 18.2,
        tempMin: 14.4,
        humidity: 88,
        pressure: 1004,
        visibility: 38,
        windSpeed: 7.1,
        windDegree: 210,
        sunrise: "06:00 AM",
        sunset: "08:45 PM"
    },
    {
        cityName: "Paris, FR",
        weatherDescription: "Clear",
        temp: 22.4,
        tempMax: 24.0,
        tempMin: 20.1,
        humidity: 70,
        pressure: 1015,
        visibility: 45,
        windSpeed: 4.2,
        windDegree: 180,
        sunrise: "06:10 AM",
        sunset: "09:10 PM"
    },
    {
        cityName: "Sydney, AU",
        weatherDescription: "Rain",
        temp: 27.3,
        tempMax: 28.5,
        tempMin: 25.7,
        humidity: 90,
        pressure: 1008,
        visibility: 41,
        windSpeed: 5.5,
        windDegree: 160,
        sunrise: "06:40 AM",
        sunset: "05:00 PM"
    },
    {
        cityName: "Boston, US",
        weatherDescription: "Mist",
        temp: 4.2,
        tempMax: 5.0,
        tempMin: 2.0,
        humidity: 95,
        pressure: 1020,
        visibility: 20,
        windSpeed: 3.3,
        windDegree: 145,
        sunrise: "05:50 AM",
        sunset: "07:50 PM"
    },
    {
        cityName: "Shanghai, CN",
        weatherDescription: "Clouds",
        temp: 10.1,
        tempMax: 11.3,
        tempMin: 8.5,
        humidity: 75,
        pressure: 1010,
        visibility: 43,
        windSpeed: 4.9,
        windDegree: 200,
        sunrise: "05:20 AM",
        sunset: "06:50 PM"
    },
    {
        cityName: "Oslo, NO",
        weatherDescription: "Clear",
        temp: -3.9,
        tempMax: -1.5,
        tempMin: -6.0,
        humidity: 60,
        pressure: 1019,
        visibility: 48,
        windSpeed: 2.1,
        windDegree: 100,
        sunrise: "04:15 AM",
        sunset: "10:15 PM"
    }
];
